name: Build Documents

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm i
      - name: Build Library
        run: npm run build
      - name: Link Library
        run: cd dist/ngx-mat-facet-search && npm link
      - name: Link Library to root
        run: npm link ngx-mat-facet-search
      - name: Build Demo 1
        run: npm run build-demo
      - name: Build Demo 2
        run: npm run build-demo
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_docs
          path: docs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_docs
